### PR TITLE
Upgrade to latest probot version

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This (hopefully) fixes the issue of using an outdated authentication token API.

### CODE REVIEW

**Comment by iHiD** [comment]
This is why the GH teams don't sync properly btw.

**Comment by iHiD** [comment]
Any idea how/where this runs?

**Comment by ErikSchierboom** [comment]
Looking at the code, it looks like it runs when the following is true for a track repo:

1. A PR is merged to `master`
1. The PR contains a modification to the `config/maintainers.json` file

**Comment by iHiD** [comment]
Do we have to update the changed version somewhere then?

**Comment by ErikSchierboom** [comment]
I have no idea. Having done some digging, it looks like there's an install page: https://docs.github.com/en/developers/apps/setting-up-your-development-environment-to-create-a-github-app#step-7-install-the-app-on-your-account

**Pull request merged**
